spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.11/sell?characterEncoding=utf-8&useSSL=false
#  打印sql语句
  jpa:
    show-sql: true
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: logs/
#  level:
#    com.gxh.sell.LoggerTest: debug